import { NextRequest, NextResponse } from "next/server"
import crypto from "crypto"
import { isConfigured, saveAppConfig } from "@/lib/config"
import { getSetupState, clearSetupState } from "@/lib/setup-state"

const BOOTSTRAP_CLIENT_ID = "14d82eec-204b-4c2f-b7e8-296a70dab67e"
const GRAPH = "https://graph.microsoft.com/v1.0"

// ─── Poll the device code flow ────────────────────────────────────────────────

async function pollForToken(
  tenantId: string,
  deviceCode: string
): Promise<
  | { status: "pending" }
  | { status: "expired" }
  | { status: "error"; message: string }
  | { status: "success"; accessToken: string; tenantId: string }
> {
  const res = await fetch(
    `https://login.microsoftonline.com/${tenantId}/oauth2/v2.0/token`,
    {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: new URLSearchParams({
        client_id: BOOTSTRAP_CLIENT_ID,
        grant_type: "urn:ietf:params:oauth:grant-type:device_code",
        device_code: deviceCode,
      }),
    }
  )

  const data = (await res.json()) as {
    access_token?: string
    tid?: string
    error?: string
    error_description?: string
  }

  if (res.ok && data.access_token) {
    // Decode the JWT to extract the tenant ID from the 'tid' claim
    const payload = JSON.parse(
      Buffer.from(data.access_token.split(".")[1], "base64url").toString("utf-8")
    ) as { tid?: string }
    return {
      status: "success",
      accessToken: data.access_token,
      tenantId: payload.tid ?? tenantId,
    }
  }

  if (data.error === "authorization_pending" || data.error === "slow_down") {
    return { status: "pending" }
  }
  if (data.error === "expired_token" || data.error === "code_expired") {
    return { status: "expired" }
  }

  return {
    status: "error",
    message: data.error_description ?? data.error ?? "Unknown token error",
  }
}

// ─── Create the app registration ─────────────────────────────────────────────

async function graphPost<T>(
  path: string,
  token: string,
  body: unknown
): Promise<T> {
  const res = await fetch(`${GRAPH}${path}`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(body),
  })
  if (!res.ok) {
    const err = (await res.json().catch(() => ({}))) as { error?: { message?: string } }
    throw new Error(
      err.error?.message ?? `Graph POST ${path} failed with ${res.status}`
    )
  }
  return res.json() as Promise<T>
}

async function createAppRegistration(
  token: string,
  tenantId: string,
  appUrl: string
): Promise<{ clientId: string; clientSecret: string; tenantId: string }> {
  const redirectUri = `${appUrl.replace(/\/$/, "")}/api/auth/callback/azure-ad`

  // 1. Create the application object
  const app = await graphPost<{ id: string; appId: string }>(
    "/applications",
    token,
    {
      displayName: "Client Support Tool",
      signInAudience: "AzureADMyOrg",
      web: {
        redirectUris: [redirectUri],
        implicitGrantSettings: { enableIdTokenIssuance: false },
      },
    }
  )

  // 2. Create a client secret (valid for 2 years)
  const now = new Date()
  const expiry = new Date(now)
  expiry.setFullYear(expiry.getFullYear() + 2)

  const secretResult = await graphPost<{ secretText: string }>(
    `/applications/${app.id}/addPassword`,
    token,
    {
      passwordCredential: {
        displayName: "Auto-generated by setup wizard",
        endDateTime: expiry.toISOString(),
      },
    }
  )

  // 3. Create the service principal (required for sign-in to work)
  await graphPost("/servicePrincipals", token, { appId: app.appId }).catch(
    (err: Error) => {
      // If the service principal already exists (race condition) that's fine
      if (!err.message.includes("already exists")) throw err
    }
  )

  return {
    clientId: app.appId,
    clientSecret: secretResult.secretText,
    tenantId,
  }
}

// ─── Route handler ────────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  if (isConfigured()) {
    return NextResponse.json({ status: "already_configured" })
  }

  const setupState = getSetupState()
  if (!setupState) {
    return NextResponse.json(
      { status: "error", message: "No active setup session. Please restart the setup." },
      { status: 400 }
    )
  }

  let appUrl: string
  try {
    const body = (await req.json()) as { appUrl?: string }
    appUrl = body.appUrl ?? ""
  } catch {
    return NextResponse.json({ status: "error", message: "Invalid JSON" }, { status: 400 })
  }

  if (!appUrl) {
    return NextResponse.json({ status: "error", message: "appUrl is required" }, { status: 400 })
  }

  // Poll Azure AD for the token
  const tokenResult = await pollForToken(setupState.tenantId, setupState.deviceCode)

  if (tokenResult.status === "pending") {
    return NextResponse.json({ status: "pending" })
  }
  if (tokenResult.status === "expired") {
    clearSetupState()
    return NextResponse.json({
      status: "error",
      message: "The device code expired. Please restart the setup.",
    })
  }
  if (tokenResult.status === "error") {
    return NextResponse.json({ status: "error", message: tokenResult.message })
  }

  // We have a token — create the app registration
  let appCreds: { clientId: string; clientSecret: string; tenantId: string }
  try {
    appCreds = await createAppRegistration(
      tokenResult.accessToken,
      tokenResult.tenantId,
      appUrl
    )
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : "Unknown error"
    return NextResponse.json({
      status: "error",
      message: `Failed to create app registration: ${message}`,
    })
  }

  // Save config and wipe the in-memory setup state
  saveAppConfig({
    ...appCreds,
    nextAuthSecret: crypto.randomBytes(32).toString("hex"),
  })
  clearSetupState()

  return NextResponse.json({ status: "success" })
}
